version: '2'
services:
  consulta-cpf-cnpj-docker:
      build:
        context: .
        args:
          - http_proxy=${http_proxy}
          - https_proxy=${http_proxy}
      volumes:
        - ./:/usr/local/consulta-cpf-cnpj-server
      ports:
          - "3000:3000"